sudo: false
language: java

env:
  - MAVEN_OPTS=-Xmx512m

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk11

before_install:
  - ./setup-atlassian-sdk.sh `pwd`
  - export PATH=opt/atlassian-plugin-sdk/bin:opt/atlassian-plugin-sdk/apache-maven-*/bin:$PATH

install:
  - atlas-mvn install

script:
  - atlas-package

notifications:
  email: false
